name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            TARGET: ubuntu
            CMD_BUILD: python setup.py bdist_wheel --plat-name manylinux1_x86_64

          - os: macos-10.15
            TARGET: macos
            CMD_BUILD: python setup.py bdist_wheel --plat-name macosx_10_13_x86_64

          - os: windows-2019
            TARGET: windows
            CMD_BUILD: python setup.py bdist_wheel --plat-name win_amd64
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install wheel setuptools

      - name: Built wheel for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - name: Install software
        run: pip install --find-links=${{github.workspace}}/dist/ raidionicsrads

      - name: Test CLI
        run: raidionicsrads --help

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/raidionicsrads-*.whl
          if-no-files-found: error
